services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure --store type=mem,size=2G
    network_mode: host
  cockroachdbtarget:
    image: cockroachdb/cockroach:latest-v23.1
    ports:
      - 8081:8080
      - 26258:26257
    command: start-single-node --insecure --store type=mem,size=2G
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    command: --gtid-mode=on --enforce-gtid-consistency=on --binlog-row-metadata=full
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
  #oracle:
  #  image: container-registry.oracle.com/database/express:21.3.0-xe
  #  platform: linux/x86_64
  #  environment:
  #    ORACLE_PWD: bobby-123
  #  ports:
  #    - "1521:1521"
  #    - "5500:5500"
