services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.1
    network_mode: host
    # It must not have storage on memory, otherwise external I/O would not be enabled.
    command: start-single-node --insecure
  cockroachdbtarget:
    image: cockroachdb/cockroach:latest-v23.1
    # We have to port forward rather than have it run on host, as the docker image
    # only support start-single-node with listen-addr on hard-coded localhost:26257,
    # which will conflict with the cockroachdb container.
    ports:
      - 26258:26257
      - 8081:8080
    command: start-single-node --insecure --store type=mem,size=2G
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    command:
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --default-authentication-plugin=mysql_native_password
      - --binlog_row_metadata=full
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /tmp/pg_data
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
  #oracle:
  #  image: container-registry.oracle.com/database/express:21.3.0-xe
  #  platform: linux/x86_64
  #  environment:
  #    ORACLE_PWD: bobby-123
  #  ports:
  #    - "1521:1521"
  #    - "5500:5500"
