{
 "title": "MOLT Dashboard",
 "description": "Dashboard for MOLT metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({__name__=~ \"molt_verify_rows_read|molt_fetch_rows_exported\"}, table)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Verify Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Tables Verified",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_verify_num_tables{category=\"verified\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Tables Missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_verify_num_tables{category=\"missing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Tables Extraneous",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_verify_num_tables{category=\"extraneous\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Verify Duration (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_verify_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Rows Verified Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (table) (molt_verify_rows_read{table=~\"$table\"})",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Number of Rows by Row Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (table, status) (molt_verify_row_verification_status{table=~\"$table\", table != \"overall\" })",
     "legendFormat": "{{table}}-{{status}}"
    }
   ]
  },
  {
   "title": "Number of Row Fixups by Category Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(table, category) (molt_verify_num_row_fixups{table=~\"$table\", table!=\"overall\"})",
     "legendFormat": "{{table}}-{{category}}"
    }
   ]
  },
  { "title": "Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Number of Tables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_num_tables", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Task Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_num_task_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Data Errors by Table",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_num_data_errors{table=\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Fetch Complete by Table",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_completion_percent{table=\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall  Fetch Duration (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_overall_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall Duration by Table (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "molt_fetch_overall_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Export Duration by Table (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_table_export_duration_ms{table=\"$table\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Import Duration by Table (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "molt_fetch_table_import_duration_ms{table=\"$table\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rows Exported Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (table) (molt_fetch_rows_exported{table=~\"$table\"})",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Number of Rows Imported Over Time (by table)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (table) (molt_fetch_rows_imported{table=~\"$table\"})",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Rate of Rows Exported Over Time (rows / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (table) (rate(molt_fetch_rows_exported{table=~\"$table\"}[5m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Rate of Rows Imported Over Time (rows / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (table) (rate(molt_fetch_rows_imported{table=~\"$table\"}[5m]))",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}