// Code generated by "stringer -type=CutoverType"; DO NOT EDIT.

package cutovertypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Consistent-1]
	_ = x[Immediate-2]
	_ = x[cutoverTypeLimit-3]
}

const _CutoverType_name = "ConsistentImmediatecutoverTypeLimit"

var _CutoverType_index = [...]uint8{0, 10, 19, 35}

func (i CutoverType) String() string {
	i -= 1
	if i < 0 || i >= CutoverType(len(_CutoverType_index)-1) {
		return "CutoverType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CutoverType_name[_CutoverType_index[i]:_CutoverType_index[i+1]]
}
