version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    working_dir: /mysql
    environment:
      MYSQL_DATABASE: "defaultdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d

  crdb:
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - ./cockroach-init:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:latest
    restart: always
    working_dir: /prometheus
    command: --config.file=prometheus.yml
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    working_dir: /grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      # TODO (rluu): put this in when we have a dashboard template.
      #  - ./grafana/dashboard.json:/grafana/dashboard/dashboard.json
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
