version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    working_dir: /mysql
    environment:
      MYSQL_DATABASE: "defaultdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./pg-init:/docker-entrypoint-initdb.d
