{
 "title": "MySQL Proxy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(${Dialect}_listener_established_connections_num,instance)"
    }
   },
   { "name": "http_path", "label": "HTTP Path", "query": { "query": "label_values(http_path)" } },
   {
    "name": "Dialect",
    "label": "Dialect",
    "query": "MySQL : mysql, PostgreSQL : pg, Cockroach : cockroach"
   }
  ]
 },
 "panels": [
  { "title": "Connection Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Connections",
   "type": "timeseries",
   "description": "Number of connections each LMS instance currently has",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "${Dialect}_listener_established_connections_num{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Source of Truth Timeline",
   "type": "state-timeline",
   "description": "Source of truth timeline for each LMS instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(instance) (${Dialect}_listener_acceptor_source_of_truth{instance=~\"$Instance\", dialect=\"${Dialect:text}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Source of Truth Total",
   "type": "stat",
   "description": "Total number of connections by source of truth",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dialect) (${Dialect}_listener_connections_source_of_truth{instance=~\"$Instance\"})",
     "legendFormat": "{{dialect}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Queries per second by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(handler_endpoint) (rate(${Dialect}_frontend_duration_seconds_count{dialect=\"handler\", instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{handler_endpoint}}"
    }
   ]
  },
  {
   "title": "Handler Latency",
   "type": "timeseries",
   "description": "Total time spent within the LMS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"handler\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"handler\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"handler\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"handler\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"handler\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Initial Source DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"${Dialect:text}\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"${Dialect:text}\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"${Dialect:text}\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"${Dialect:text}\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=\"${Dialect:text}\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Initial Target DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=~\"Cockroach\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=~\"Cockroach\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=~\"Cockroach\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=~\"Cockroach\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(${Dialect}_frontend_duration_seconds_bucket{dialect=~\"Cockroach\", instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Shadowing Error Mismatches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(${Dialect}_shadower_err_mismatches_num[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Translation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(${Dialect}_backend_crdb_translations_num{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Orchestrator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Availability %",
   "type": "timeseries",
   "description": "Endpoint availability percentage over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "(1 - (sum(http_server_duration_ms_count{ http_status_code!=\"200\", http_path=~\"/api/v1/.*\" }) / sum(http_server_duration_ms_count{ http_path=~\"/api/v1/.*\" }))) * 100",
     "legendFormat": "Availability %"
    }
   ]
  },
  {
   "title": "Individual Endpoint Latency (use path filter)",
   "type": "timeseries",
   "description": "The individual distribution for each orchestrator endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, http_path, http_verb) (rate(http_server_duration_ms_bucket{http_path=~\"$http_path\"}[$__rate_interval])))",
     "legendFormat": "p50 {{http_verb}} {{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, http_path, http_verb) (rate(http_server_duration_ms_bucket{http_path=~\"$http_path\"}[$__rate_interval])))",
     "legendFormat": "p75 {{http_verb}} {{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, http_path, http_verb) (rate(http_server_duration_ms_bucket{http_path=~\"$http_path\"}[$__rate_interval])))",
     "legendFormat": "p90 {{http_verb}} {{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_path, http_verb) (rate(http_server_duration_ms_bucket{http_path=~\"$http_path\"}[$__rate_interval])))",
     "legendFormat": "p95 {{http_verb}} {{http_path}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_path, http_verb) (rate(http_server_duration_ms_bucket{http_path=~\"$http_path\"}[$__rate_interval])))",
     "legendFormat": "p99 {{http_verb}} {{http_path}}"
    }
   ]
  },
  {
   "title": "Orchestrator Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability % (by endpoint)",
     "type": "timeseries",
     "description": "Endpoint availability percentage over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(http_server_duration_ms_count{ http_status_code=~\"2..\", http_path=~\"$http_path\" }) by (http_path, http_verb) / sum(http_server_duration_ms_count{ http_path=~\"$http_path\" }) by (http_path, http_verb) * 100",
       "legendFormat": "{{http_verb}} {{http_path}}"
      }
     ]
    },
    {
     "title": "Sum of Status Code Count",
     "type": "timeseries",
     "description": "Sum of count of status codes at given times",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "sum by (http_status_code) (http_server_duration_ms_count{ http_path=~\"/api/v1/.*\" })",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Increase Status Code (last 1m)",
     "type": "timeseries",
     "description": "Sum of count of status codes at given times",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by (http_status_code) (increase(http_server_duration_ms_count{ http_path=~\"/api/v1/.*\" }[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status Codes",
     "type": "piechart",
     "description": "Status Code Total Counts",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_duration_ms_count{ http_path=~\"/api/v1/.*\" }) by (http_status_code)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}