name: E2E Tests

# Runs nightly at UTC midnight
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual runs

env:
  GO_VERSION: "1.21"

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      COVER_OUT: coverage.out

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up dependencies
        run: ./scripts/e2etest-setup.sh

      - name: Run E2E Tests
        run: |
          echo 'current commit SHA: ${{ github.event.pull_request.head.sha }}"
          go test -v -timeout 30m ./e2e -e2e-enabled