name: release-helm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create release directory
      run: mkdir -p artifacts
    - uses: azure/setup-helm@v3
      with:
        version: 'v3.12.2'
      id: install
    - name: Check helm version
      run: helm version && ls ./charts/lms
    - name: Package and index chart
      # TODO: merge the old index with this one: curl the old one => merge option.
      # TODO: package with the version number
      run: |
        helm package ./charts/lms --destination artifacts/
        helm repo index artifacts/ --url https://molt.binaries.com/charts 
    - name: Check contents of artifacts
      run: |
        cat ./artifacts/index.yaml
        ls ./artifacts
    # TODO: set the URL conditionally based on environment
    # TODO: add GCS storage upload


