name: release-helm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-chart:
    environment: ${{ github.event_name == 'release' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create release directory
      run: rm -rf artifacts && mkdir -p artifacts
    - uses: azure/setup-helm@v3
      with:
        version: 'v3.12.2'
      id: install
    - name: Check helm version
      run: helm version && ls ./charts/lms
    - name: Package and index chart
      # Default behavior of --merge with a non-existent file is to merge with a new empty file.
      # So we remove the file created from failed curl.
      # --fail-with-body will return a bash exit code if the HTTP status code is >= 400.
      run: |
        curl --fail-with-body -o artifacts/old-index.yaml -s '${{ vars.CHART_URL }}/lms/charts/index.yaml' || rm artifacts/old-index.yaml
        helm package ./charts/lms --destination artifacts/ --version ${{ startsWith(github.ref_name, 'v') && github.ref_name || 'v0.0.0' }}
        helm repo index artifacts/ --url '${{ vars.CHART_URL }}/lms/charts' --merge "artifacts/old-index.yaml"
    - name: Check contents of artifacts
      run: |
        cat ./artifacts/index.yaml
        ls ./artifacts
    - name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: "${{ vars.WORKLOAD_IDENTITY_PROVIDER }}"
        service_account: "${{ vars.GCP_SERVICE_ACCOUNT }}"
    - name: Upload to GCP bucket
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: 'artifacts'
        destination: '${{ vars.GCS_BUCKET }}/lms/charts'
        parent: false
        headers: |-
          cache-control:public, max-age=60 


